config/routes.rb
PdlPrescription::Application.routes.draw do
  
  
  devise_for :users, :controllers => { 
    :sessions => "sessions",
    :registrations => "registrations" 
  } do 
    get "login", :to => 'sessions#new'  
  end  
  
  root :to => 'pages#home'
    
  match '/about',         :to => 'pages#about'
  match '/contact',       :to => 'pages#contact'
  match '/how_it_works',  :to => 'pages#how_it_works'
  match '/blog',          :to => 'pages#blog'
  match '/support',       :to => 'pages#support' 
  match '/products',      :to => 'pages#products'  
  match '/purchase',      :to => 'pages#purchase'
  match '/service',       :to => 'pages#service'
     
  get "pages/products"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/how_it_works"
  get "pages/blog"
  get "pages/support"
  get "pages/purchase"
  get "pages/service"
  get "pages/prescription"

  resources :users
  resources :prescriptions
  resources :tasks

end

app/models/prescription.rb
class Prescription
  include MongoMapper::Document

  key :p_id, String
  key :job_array, Array
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
before_filter :authenticate_user!

  # GET /prescriptions
  # GET /prescriptions.xml
  def index
    @prescriptions = Prescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prescriptions }
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.xml
  def show
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prescription }
    end
  end

  # GET /prescriptions/new
  # GET /prescriptions/new.xml
  def new
    @prescription = Prescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prescription }
    end
  end

  # GET /prescriptions/1/edit
  def edit
    @prescription = Prescription.find(params[:id])
  end

  # POST /prescriptions
  # POST /prescriptions.xml
  def create
    @prescription = Prescription.new(params[:prescription])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to(@prescription, :notice => 'Prescription was successfully created.') }
        format.xml  { render :xml => @prescription, :status => :created, :location => @prescription }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prescription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prescriptions/1
  # PUT /prescriptions/1.xml
  def update
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      if @prescription.update_attributes(params[:prescription])
        format.html { redirect_to(@prescription, :notice => 'Prescription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prescription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.xml
  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to(prescriptions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<h1>Listing prescriptions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr>
    <td><%= link_to 'Show', prescription %></td>
    <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
    <td><%= link_to 'Destroy', prescription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>