config/routes.rb
PdlPrescription::Application.routes.draw do
  
  
  devise_for :users, :controllers => { 
    :sessions => "sessions",
    :registrations => "registrations" 
  } do 
    get "login", :to => 'sessions#new'  
  end  
  
  root :to => 'pages#home'
    
  match '/about',         :to => 'pages#about'
  match '/contact',       :to => 'pages#contact'
  match '/how_it_works',  :to => 'pages#how_it_works'
  match '/blog',          :to => 'pages#blog'
  match '/support',       :to => 'pages#support' 
  match '/products',      :to => 'pages#products'  
  match '/purchase',      :to => 'pages#purchase'
  match '/service',       :to => 'pages#service'
     
  get "pages/products"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/how_it_works"
  get "pages/blog"
  get "pages/support"
  get "pages/purchase"
  get "pages/service"
  get "pages/prescription"

  resources :users
  resources :prescriptions
  resources :tasks

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="footer">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://dentaltown.com/">News</a></li>
      <li><%= link_to "Support", support_path%></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header>


	<br></br>
    <nav class="upperNav">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", support_path %></li>
      </ul>
    </nav>
    <% main_logo = image_tag("20110301_parthenon_logo.png", :alt => "PDL", :class => "round logo", :title =>"PDL") %>
	<%= link_to main_logo, root_path %>
	<div>
		<nav class ="mainNav">
			<ul>
				<li><%= link_to "Products", products_path %></li>
				<li><%= link_to "Dental Services", service_path %></li>
				<li class = "shopButton"><%= link_to "Shop", purchase_path %></li>				
			</ul>
		</nav>
	</div>


  </header>

app/views/layouts/_stylesheet.html.erb
    <%= csrf_meta_tag %>
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
	<%= stylesheet_link_tag 'css/smoothness/jquery-ui-1.8.14.custom' %>    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js" %>
	<%= javascript_include_tag 'jquery-ui-1.8.14.custom.min.js' %>

app/views/layouts/_top_nav.html.erb
<nav id="ltb" class="sessionNav" role="navigation">
	<ul>
		<% if user_signed_in? %>
		  <li>Signed in as <%= current_user.email %>  Not you?
		  <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></li>
		<% else %>
 		  <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>


	<%= render 'layouts/stylesheet' %>

  </head>
  <body>
	<%= render 'layouts/top_nav' %>
	
	<div class="container">
	     <%= render 'layouts/header' %>
	     <% flash.each do |key, msg| %>
		    <%= content_tag(:div, msg, :class => "flash_#{key}") %>
		 <% end %>
		 <!-- <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
       	 -->
	      <section class="round">
	        <%= yield %>
	      </section>
		 <%= render 'layouts/footer' %>
      	 <%= debug(params) if Rails.env.development? %>
	    </div>
  </body>
</html>